Repository EternalHeartTeam/leetcode-practice, pull requests merged in 2024-03, with the labels that each got.

#20 docs: add star history
  README.md
Labels: Core Team, md

#22 ci(npm): cli release
  .github/workflows/contributors.yml
  .github/workflows/pr-add-label.yml
  .github/workflows/release-cli.yml
  .npmignore
  .npmrc
  README.md
  bin/release.js
  common/utils/file/getRootPath.js
  package.json
Labels: Core Team, md, js, yml, npmignore, npmrc, json

#23 ci(npm): cli release
  .github/workflows/contributors.yml
  .github/workflows/pr-add-label.yml
  .github/workflows/release-cli.yml
  .npmignore
  .npmrc
  .release-it.json
  CHANGELOG.md
  README.md
  common/utils/file/getRootPath.js
  package.json
  scripts/release.js
Labels: Core Team, md, js, yml, npmignore, npmrc, json

#25 fix: realm-compatible-problem
  package.json
Labels: json

#26 feat:instead new docs
  README.md
  README_CN.md
  README_JP.md
  directory.md
  docs/README_CN.md
  docs/README_JP.md
  docs/README_KR.md
  docs/update.md
  resources/images/create-finish.png
  resources/images/create-new-by-template.png
  resources/images/fulfill-template-new.png
  resources/images/generating-your-template.png
  resources/images/github-fork.png
  resources/images/github-forked.png
  resources/images/github-forking.png
  resources/images/leetcode-practice-github.png
  resources/images/template-page.png
Labels: Core Team, md, png

#29 docs: optimize lang description
  README.md
  README_CN.md
  README_JP.md
Labels: Core Team, md

#30 ci: create dependabot.yml
  .github/dependabot.yml
Labels: Core Team, yml

#37 docs: support for document language switching
  CONTRIBUTORS.md
  CONTRIBUTORS_CN.md
Labels: Core Team, md

#38 ci(release): modify ci to release when tag add and change the release…
  .github/workflows/release-cli.yml
  .release-it.json
Labels: Core Team, md, yml, json

#40 docs: simplified doc
  README.md
  README_CN.md
  README_JP.md
Labels: Core Team, md

#42 chore(release): set new branch by correct command
  .release-it.json
Labels: Core Team, md, js, yml, json, png

#45 chore: remove unsless code
  common/utils/cli-utils/commonMode.js
Labels: Core Team, js

#44 docs: simplifying the npm install command
  README.md
  README_CN.md
  README_JP.md
Labels: Core Team, md

#46 ci(test): update file name
  .github/workflows/ci.yml
Labels: Core Team, yml

#49 chore(pre-commit): modify command
  .husky/pre-commit
Labels: Core Team, husky/pre-commit

#53 chore: tiny modify some files for better performance
  .release-it.json
  CHANGELOG.md
  bin/lf.js
  bin/lk.js
  common/constants/manager.const.js
  common/utils/cli-utils/commonMode.js
  common/utils/loading/loading.js
  common/utils/update/updateByEnv.js
  common/view/update.view.js
  package.json
  scripts/loading.js
  scripts/release.js
  scripts/update.js
Labels: Core Team, md, js, json

#62 Filter out the front-end learn plan list
  common/view/finder.view.js
Labels: Core Team, js

#64 feat: get 'jsonExampleTestcases', 'exampleTestcases'
  common/utils/question-handler/getQuestionDetail.js
  resources/headers/questionDetailJson.js
  test/create.spec.js
  test/parseFilePath.spec.js
Labels: Core Team, js

#65 feat lf command select mode
  common/utils/question-handler/getQuestionListCodeBy.js
  common/utils/question-handler/getQuestionListCodeBySlug.js
  common/utils/store/controller/allQuestion.js
  common/view/finder.view.js
Labels: Core Team, js

#69 feat: add pr and issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: Core Team, md

#70 chore: Configuring CONTRIBUTING
  .github/CONTRIBUTING.md
  .github/CONTRIBUTING_CN.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/pull_request_template.md
  README.md
  README_CN.md
  README_JP.md
Labels: Core Team, md
